{% set version = "0.8-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-numbers
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/numbers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/numbers/numbers_{{ version }}.tar.gz
  sha256: 77d5dedb7f953689ab9e89c14e673c0c8f644c8b392fab4ee4fb793930ad220b

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('numbers')"           # [not win]
    - "\"%R%\" -e \"library('numbers')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=numbers
  license: GPL (>= 3)
  summary: " Provides number-theoretic functions for factorization, prime  numbers, twin primes, primitive roots, modular logarithm and inverses, extended GCD, Farey series and continuous fractions. Includes Legendre and Jacobi symbols, some divisor functions, Euler's Phi function, etc."
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: numbers
# Type: Package
# Title: Number-Theoretic Functions
# Version: 0.7-1
# Date: 2018-05-16
# Author: Hans Werner Borchers
# Maintainer: Hans W. Borchers <hwborchers@googlemail.com>
# Depends: R (>= 3.1.0)
# Suggests: gmp (>= 0.5-1)
# Description:  Provides number-theoretic functions for factorization, prime  numbers, twin primes, primitive roots, modular logarithm and inverses, extended GCD, Farey series and continuous fractions. Includes Legendre and Jacobi symbols, some divisor functions, Euler's Phi function, etc.
# License: GPL (>= 3)
# Repository: CRAN
# Repository/R-Forge/Project: optimist
# Repository/R-Forge/Revision: 453
# Repository/R-Forge/DateTimeStamp: 2018-05-16 18:50:43
# Date/Publication: 2018-05-17 08:49:01 UTC
# NeedsCompilation: no
# Packaged: 2018-05-16 19:15:14 UTC; rforge
