travis:
  secure:
    BINSTAR_TOKEN: L3FaYQeptXs7MsYPNOF5x4T2SYiSLOEMLAFwh767P6oo/wLD01jrpVhYDiczkzGDBA251BkQi8HiSP1ggDB+gl9d9yA5Y5sFfPNiczT1UFxmD3icpudhtE2tMUixVhP7FWI2vSgHvitn3U40DAyQXOq5WVTXahsXz8qFRDfTslgHi3uYSzLtZnvjEVH1Fcjc+/oSwudbCFrPFclGvR1MrY96Flpowz6RpRYvg91S1XVdSYLyq6Rwq4Qju4dwsTyZUDNvsEwiLqyOVVKWgZJSfU2+jTN/kn/hOZRnNZMqreroB2OoUVxeKAWK4Xzti4lIa+9szemnh74SBe8CG2u4rpOeWve2LI+QAxLGGvM/Zcq9wbxNW2l0U8WDC8hgaN/pwJmtoJAd0Iai7tn53QK1tLgkQhLuaPkvpEq8jo3NmyRhn9xwGZVeDaGjMDoPVFlhbjxcc7BREefjdWy7Wj2R6O1gvHtzQu9UZyWiateZ5d0dP7wztkGm3Fy3/ulsGWECnMS9nnOOpU4FESctg+lWodIFk67djwcXOXoz2/ovhBbRwDhsZ9NJkF2/Tuodd2jNGjkJb+VSY1FUDb5Vg2juGUiJsqpLeb3Ek2/dHSC7hiAHXfuUoqoJ1JauXxWeai+s4b94veXobGIbalwRJXxn4DMUa8Uo06hv+EG/fOQ6B5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
